server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orchestratorDb?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      apache:
        kafka: OFF